### ISSUE TITLE
Doesnt' jump: Game Over on the first obstacle.

### ISSUE THREAD

**Issue by franciscocorrales** [AeonAxan/chrome-dino-game-bot#1]
It is not working for me. The runner never jumps. It hits the first obstacle.

I tried to execute the script 
-before starting the game
-while playing the game
-after starting the game

I can see a lot of logs in the console.

**Comment by daviidmart** [comment]
Yea the code not work

**Comment by AeonAxan** [comment]
Works now. Had to update the eye coordinates. It changes when chrome updates the game a bit.

**Comment by franciscocorrales** [comment]
Doesn't work.
Video: https://screencast.com/t/IPWLzu3DepxS
Chrome: Version 64.0.3282.167 (Official Build) (64-bit)
